src/BookList.Web/Models/JtGridModel.cs
using Castle.Core.Internal;

namespace BookList.Web.Models
{
    public class JtGridModel
    {
        private const string defaultSorting = "Title ASC";
        private string sorting;

        public string JtSorting
        {
            get { return sorting.IsNullOrEmpty() ? defaultSorting : sorting; }
            set { sorting = value; }
        }
    }
}

src/BookList.Web/Controllers/AuthorController.cs
using System.Web.Mvc;
using BookList.Core.Models;
using BookList.Core.Repositories;

namespace BookList.Web.Controllers
{
    public class AuthorController : Controller
    {
        protected readonly IAuthorRepository authorRepository;

        public AuthorController(IAuthorRepository authorRepository)
        {
            this.authorRepository = authorRepository;
        }

        [HttpPost]
        public JsonResult AuthorList(int bookId)
        {
            var authors = authorRepository.GetAuthorsOfBook(bookId);
            return Json(new { Result = "OK", Records = authors });
        }

        [HttpPost]
        public JsonResult CreateAuthor(Author author)
        {
            if (!ModelState.IsValid)
            {
                return Json(new
                {
                    Result = "ERROR",
                    Message = "Form is not valid! " +
                              "Please correct it and try again."
                });
            }

            var addeAuthor = authorRepository.AddAuthor(author);
            return Json(new { Result = "OK", Record = addeAuthor });
        }

        [HttpPost]
        public JsonResult UpdateAuthor(Author author)
        {
            if (!ModelState.IsValid)
            {
                return Json(new
                {
                    Result = "ERROR",
                    Message = "Form is not valid! " +
                              "Please correct it and try again."
                });
            }

            authorRepository.UpdateAuthor(author);
            return Json(new { Result = "OK" });
        }

        [HttpPost]
        public JsonResult DeleteAuthor(int authorId)
        {
            authorRepository.DeleteAuthor(authorId);
            return Json(new { Result = "OK" });
        }
    }
}

src/BookList.Web/Controllers/BookController.cs
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using BookList.Core.Models;
using System.Web.Mvc;
using BookList.Core.Repositories;
using Castle.Core.Internal;

namespace BookList.Web.Controllers
{
    public class BookController : Controller
    {
        protected readonly IBookRepository bookRepository;

        private readonly byte[] placeholderImage = ImageToByte(Images.PlaceholderBook);
        private readonly string placeholderImageType = "image/png";

        public BookController(IBookRepository bookRepository)
        {
            this.bookRepository = bookRepository;
        }

        [HttpPost]
        public JsonResult UploadBookImage(HttpPostedFileBase coverimg, int bookId)
        {
            var book = bookRepository.GetAllBooks().First(x => x.BookId.Equals(bookId));

            book.ImageType = coverimg.ContentType;
            using (var binaryReader = new BinaryReader(coverimg.InputStream))
            {
                book.Image = binaryReader.ReadBytes(coverimg.ContentLength);
            }

            bookRepository.UpdateBook(book);
            return Json(new { Result = "OK" });
        }

        [HttpGet]
        public FileResult GetBookImage(int bookId)
        {
            var book = bookRepository.GetAllBooks().First(x => x.BookId.Equals(bookId));

            return File(book.Image ?? placeholderImage, book.ImageType ?? placeholderImageType);
        }

        [HttpPost]
        public JsonResult BookList(string jtSorting)
        {
            var books = jtSorting.IsNullOrEmpty()
                ? bookRepository.GetAllBooks()
                : bookRepository.GetBooksSorted(jtSorting);
            return Json(new { Result = "OK", Records = books, Sorting = jtSorting });
        }

        [HttpPost]
        public JsonResult CreateBook(Book book)
        {
            if (!ModelState.IsValid)
            {
                return Json(new
                {
                    Result = "ERROR",
                    Message = "Form is not valid! " +
                              "Please correct it and try again."
                });
            }

            var addedBook = bookRepository.AddBook(book);
            return Json(new { Result = "OK", Record = addedBook });
        }

        [HttpPost]
        public JsonResult UpdateBook(Book book)
        {
            if (!ModelState.IsValid)
            {
                return Json(new
                {
                    Result = "ERROR",
                    Message = "Form is not valid! " +
                              "Please correct it and try again."
                });
            }

            bookRepository.UpdateBook(book);
            return Json(new { Result = "OK" });
        }

        [HttpPost]
        public JsonResult DeleteBook(int bookId)
        {
            bookRepository.DeleteBook(bookId);
            return Json(new { Result = "OK" });
        }

        private static byte[] ImageToByte(Image img)
        {
            byte[] byteArray;
            using (var stream = new MemoryStream())
            {
                img.Save(stream, System.Drawing.Imaging.ImageFormat.Png);
                stream.Close();

                byteArray = stream.ToArray();
            }
            return byteArray;
        }
    }
}

src/BookList.Web/Controllers/HomeController.cs
using System.Web.Mvc;
using BookList.Web.Models;

namespace BookList.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index(JtGridModel model)
        {
            return View(model);
        }
    }
}

src/BookList.Web/Views/Home/Index.cshtml
@using System.Web.Optimization
@model BookList.Web.Models.JtGridModel

<!DOCTYPE html>
<html>
<head>
    @Styles.Render("~/bundles/css/jqueryui")
    @Styles.Render("~/bundles/css/jtable")
    @Scripts.Render("~/bundles/js/jquery")
    @Scripts.Render("~/bundles/js/jqueryui")
    @Scripts.Render("~/bundles/js/jtable")
    <script src="~/Scripts/index.js"></script>
</head>
<body>
    <div id="BookTable"></div>
</body>
</html>

<script type="text/javascript">
    $(document).ready(function () {
        $('#BookTable').jtable({
            title: 'The Book List',
            paging: false,
            sorting: true,
            defaultSorting: '@Model.JtSorting',
            actions: {
                listAction: '@Url.Action("BookList", "Book")',
                deleteAction: '@Url.Action("DeleteBook", "Book")',
                updateAction: '@Url.Action("UpdateBook", "Book")',
                createAction: '@Url.Action("CreateBook", "Book")'
            },
            fields: {
                BookId: {
                    key: true,
                    create: false,
                    edit: false,
                    list: false
                },
                Title: {
                    title: 'Title',
                    sorting: true,
                    inputClass: 'validate[required, maxSize[30]]',
                    width: '20%'
                },
                PublishDate: {
                    title: 'Publish Date',
                    sorting: true,
                    inputClass: 'validate[required, min[1800]]',
                    width: '15%'
                },
                Publisher: {
                    title: 'Publisher',
                    sorting: false,
                    inputClass: 'validate[maxSize[30]]',
                    width: '20%'
                },
                Pages: {
                    title: 'Pages',
                    sorting: false,
                    inputClass: 'validate[required, min[0], max[10000]]',
                    width: '5%'
                },
                Isbn: {
                    title: 'ISBN',
                    sorting: false,
                    inputClass: 'validate[required, funcCall[checkIsbn]]',
                    width: '15%'
                },
                Authors: {
                    title: 'Authors',
                    width: '10%',
                    sorting: false,
                    edit: false,
                    create: false,
                    display: function(bookData) {
                        var $authorsLink = $('<a href="#" title="Edit Authors">Edit Authors</a>');
                        $authorsLink.click(function() {
                            var tr = $(this).parents("tr"),
                                isChildRowOpen = $('#BookTable').jtable("isChildRowOpen", tr);
                            if (isChildRowOpen) {
                                $($('#BookTable').jtable("getChildRow", tr)).slideUp();
                                return;
                            } else {
                                $('#BookTable').jtable('openChildTable',
                                    $authorsLink.closest('tr'),
                                    {
                                        title: bookData.record.Title + ' - Authors',
                                        actions: {
                                            listAction: '@Url.Action("AuthorList", "Author")' + '?bookId=' + bookData.record.BookId,
                                            deleteAction: '@Url.Action("DeleteAuthor", "Author")',
                                            updateAction: '@Url.Action("UpdateAuthor", "Author")',
                                            createAction: '@Url.Action("CreateAuthor", "Author")'
                                        },
                                        fields: {
                                            AuthorId: {
                                                key: true,
                                                create: false,
                                                edit: false,
                                                list: false
                                            },
                                            FirstName: {
                                                title: 'First Name',
                                                inputClass: 'validate[required, maxSize[20]]'
                                            },
                                            LastName: {
                                                title: 'Last Name',
                                                inputClass: 'validate[required, maxSize[20]]'
                                            }
                                        },
                                        formCreated: function(event, data) {
                                            data.form.validationEngine();
                                        },
                                        formSubmitting: function(event, data) {
                                            return data.form.validationEngine('validate');
                                        },
                                        formClosed: function(event, data) {
                                            data.form.validationEngine('hide');
                                            data.form.validationEngine('detach');
                                        }
                                    }, function(data) { //opened handler
                                        data.childTable.jtable('load');
                                    });
                            }
                        });
                        return $authorsLink;
                    }
                },
                image_upload: {
                    title: 'Book Image',
                    width: '15%',
                    list: true,
                    create: false,
                    edit: false,
                    display: function(data) {
                        return '<div id=' + data.record.BookId + '><form id="form' + data.record.BookId + '" method="post" enctype="multipart/form-data" action="@Url.Action("UploadBookImage", "Book")"><input type="file" name="coverimg" id="' + data.record.BookId + '" class="upload"/><input type="hidden" name="bookId" value="' + data.record.BookId + '"/></form></div><div id="preview' + data.record.BookId + '"><img width="40%" height="40%" src="@Url.Action("GetBookImage", "Book")' + '?bookId=' + data.record.BookId + '"/></div>';
                    }
                }
            },
            formCreated: function(event, data) {
                data.form.validationEngine();
            },
            formSubmitting: function(event, data) {
                return data.form.validationEngine('validate');
            },
            formClosed: function(event, data) {
                data.form.validationEngine('hide');
                data.form.validationEngine('detach');
            },
            recordsLoaded: function(event, data) {
                insertParam('jtSorting', data.serverResponse.Sorting);

                $('.upload').on('change', function () {
                    var id = this.id;
                    $("#preview" + id).html('');
                    $("#preview" + id).html('<img src="Content/loader.gif" alt="Uploading...."/>');
                    $("#form" + id).ajaxSubmit({
                        success: function(data) {
                            $('#preview' + id).html("<img width='40%' height='40%' src='@Url.Action("GetBookImage", "Book")" + "?bookId=" + id + '&_=' + new Date().getTime() + "'/>");
                        },
                        error: function(data) {
                            $("#preview" + id).html('');
                        }
                    });

                });
            }
        });

        $('#BookTable').jtable('load');
    });
</script>